---

hostname: hq-wan-mpls

type: 
  site: hub
  iwan: mpls

vrfs:
  - vrf_name: IWAN-MPLS-1

static_routes:
  
  - route_name: mpls-default
    vrf: IWAN-MPLS-1
    destination:
      prefix: 0.0.0.0
      mask: 0.0.0.0
    forwarding_router: 10.255.20.1

eigrp_instances:
  - instance: ent_eigrp
    summary_addresses:
    - 172.20.0.0/16

loopback_interfaces:
  
  - interface: Loopback0
    state_enabled: true
    description: mgmt
    ip:
      address: 172.20.255.1/30

lan_interfaces:
  
  - interface: GigabitEthernet3
    state_enabled: true
    description: hq-core_ge0/2
    ip:
      address: 172.20.0.1/30
    cdp_enabled: true

wan_interfaces:
  
  - interface: GigabitEthernet2
    state_enabled: true 
    description: mpls_provider_ge0/2
    bandwidth: 50000
    vrf: IWAN-MPLS-1
    ip:
      address: 10.255.20.2/30
    
tunnel_interfaces:
  
  - interface: Tunnel10
    profile: dmvpn_mpls_1
    state_enabled: true
    bandwidth: 100000
    ip:
      address: 172.16.101.1/24
    source: GigabitEthernet2
