- name: gather IOS facts
  ios_facts:
    gather_subset: interfaces
    provider: "{{ ioscli }}"
  register: ios_facts_results

- set_fact: interface_facts={{ios_facts_results.ansible_facts.ansible_net_interfaces}}

- debug:
    msg: "{{interface_facts}}"